---
- name: Setup MF server on a Linux server
  hosts: servers
  become: true
  vars_files:
    - vars.yml
  vars:
    game_path: "{{ install_path }}/MobileForces"

  tasks:
    - name: Ensure server user exists
      ansible.builtin.user:
        name: "{{ server_user }}"

    - name: Create MF server
      ansible.builtin.include_tasks: 
        file: tasks/create_mf_server.yml

    - name: Create apache server for FastDL
      ansible.builtin.include_tasks:
        file: tasks/create_apache_server.yml

    - name: Compress all game files for FastDL
      ansible.builtin.shell: "sudo -u {{ server_user }} bash {{ game_path }}/System/compress.sh"

    - name: Start MF server
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - mobileforces
        - mobileforces-masterserver

  handlers:
    - ansible.builtin.import_tasks: handlers/mf.yml
    - ansible.builtin.import_tasks: handlers/apache.yml
