---
- name: Setup MF server on a Linux server
  hosts: servers
  become: true
  vars_files:
    - vars.yml
  vars:
    game_path: "{{ install_path }}/MobileForces"
    website_path: "{{ install_path }}/website"

  tasks:
    - name: Ensure server user exists
      ansible.builtin.user:
        name: "{{ server_user }}"

    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: "755"
      loop:
        - "{{ install_path }}"
        - "{{ website_path }}"

    - name: Install common dependencies
      ansible.builtin.package:
        name: unzip
        state: latest
        update_cache: yes

    - name: Create MF masterserver
      ansible.builtin.include_tasks: 
        file: tasks/create_mf_masterserver.yml

    - name: Create MF gameserver
      ansible.builtin.include_tasks: 
        file: tasks/create_mf_gameserver.yml

    - name: Create apache webserver (site + FastDL)
      ansible.builtin.include_tasks:
        file: tasks/create_apache_webserver.yml

    - name: Start MF services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - mobileforces-masterserver
        - mobileforces
        - mobileforces-fastdl

  handlers:
    - ansible.builtin.import_tasks: handlers/systemctl.yml
