---
- name: Setup MF server on a Linux server
  hosts: servers
  become: true
  vars:
    apache: "{{ 'apache2' if ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' else 'httpd' }}"
    game_path: "{{ install_path }}/MobileForces"
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure server user exists
      ansible.builtin.user:
        name: "{{ server_user }}"

    - name: Create MF server
      ansible.builtin.include_tasks: 
        file: tasks/create_mf_server.yml

    - name: Create apache server for FastDL
      ansible.builtin.include_tasks:
        file: tasks/create_apache_server.yml

    - name: Compress all game files for FastDL
      ansible.builtin.shell: "sudo -u {{ server_user }} bash {{ game_path }}/System/compress.sh"

    - name: Start MF server
      ansible.builtin.service:
        name: mobileforces
        state: started
        enabled: yes

  handlers:
    - ansible.builtin.import_tasks: handlers/mf.yml
    - ansible.builtin.import_tasks: handlers/apache.yml
