---
- name: Install apache and related packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - libapache2-mpm-itk
    - libapache2-mod-php
    - php-sqlite3
    - python3-certbot-apache

- name: Create virtual host for the mf website
  ansible.builtin.template:
    src: templates/webserver/vhosts/mobileforces.j2
    dest: /etc/apache2/sites-available/mobileforces.conf
    mode: "644"

- name: Ensure website directories exist
  ansible.builtin.file:
    path: "{{ website_path }}/{{ item }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "755"
  loop:
    - ""
    - admin
    - includes/
    - includes/php/
    - includes/css
    - includes/images
    - includes/js

- name: Copy static files into the webserver folder
  ansible.builtin.copy:
    src: "templates/webserver/website/{{ item[0] }}"
    dest: "{{ website_path }}/{{ item[1] }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "644"
  loop:
    - [index.php, index.php]
    - [stats.php, stats.php]
    - [donate_notify.php, donate_notify.php]
    - [favicon.ico, favicon.ico]
    - [admin/, admin/]
    - [includes/css/, includes/css/]
    - [includes/images/, includes/images/]
    - [includes/js/, includes/js/]
    - [includes/php/body.php, includes/php/body.php]
    - [includes/php/db.php, includes/php/db.php]

- name: Copy dynamic website files
  ansible.builtin.template:
    src: "templates/webserver/website/{{ item[0] }}"
    dest: "{{ website_path }}/{{ item[1] }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "644"
  loop:
    - [includes/php/kofi.j2, includes/php/kofi.php]
    - [includes/php/cookies.j2, includes/php/cookies.php]

- name: Remove previous verisons of elFinder
  ansible.builtin.shell: "rm -rf {{ website_path }}/admin/elFinder-*"

- name: Extract elFinder zip onto server
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ website_path }}/admin/"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "755"
  with_fileglob:
    - "templates/webserver/elFinder-*.zip"

- name: Install & configure elFinder for MF
  ansible.builtin.shell: cd "{{ website_path }}"/admin/elFinder-*/php && mv connector.minimal.php-dist connector.minimal.php && sed -i "s/uploadAllow'   => array(/uploadAllow'   => array('application\/octet-stream', /g" connector.minimal.php

- name: Create symbolic links for elFinder
  ansible.builtin.shell: "cd {{ website_path }}/admin/elFinder-*/files && ln -f -s {{ item }} ."
  loop:
    - "{{ game_path }}"
    - "{{ website_path }}"

- name: Request LE certificate
  ansible.builtin.shell: "certbot --apache -n --email {{ ServerAdmin }} --agree-tos --no-redirect -d {{ ServerName }}"

- name: Allow the website to restart game services
  ansible.builtin.template:
    src: templates/webserver/scripts/01-mobileforces.j2
    dest: /etc/sudoers.d/01-mobileforces
    owner: root
    group: root
    mode: "440"

- name: Enable only the mobileforces website
  ansible.builtin.shell: a2dissite 000-default.conf && a2ensite mobileforces.conf
  notify: Reload apache
