---
- name: Prepare to install wine
  ansible.builtin.shell: dpkg --add-architecture i386 && wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add - && wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources

- name: Install wine
  ansible.builtin.package:
    name: winehq-stable
    state: latest
    install_recommends: yes

- name: Extract Mobile Forces zip onto server if the game path doesn't exist
  ansible.builtin.unarchive:
    creates: "{{ game_path }}/"
    src: "{{ mf_path }}"
    dest: "{{ install_path }}/"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "774"

- name: Copy files into the System folder
  ansible.builtin.template:
    src: "templates/gameserver/scripts/{{ item[0] }}"
    dest: "{{ game_path }}/System/{{ item[1] }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "774"
  loop:
    - [compress.j2, compress.sh]
    - [dedicated.sh, dedicated.sh]

- name: Set admin info
  ansible.builtin.replace:
    path: "{{ game_path }}/System/MobileForces.ini"
    regexp: "{{ item[0] }}=.*"
    replace: "{{ item[0] }}={{ item[1] }}"
  loop:
    - [AdminEmail, "{{ ServerAdmin }}"]
    - [AdminPassword, "{{ AdminPassword }}"]

- name: Create service files for the mf server
  ansible.builtin.template:
    src: "templates/gameserver/services/{{ item[0] }}"
    dest: "/etc/systemd/system/{{ item[1] }}"
    mode: "644"
  loop:
    - [mobileforces.j2, mobileforces.service]
    - [mobileforces-fastdl.j2, mobileforces-fastdl.service]
  notify:
    - Reload systemctl
