---
- name: Ensure masterserver directory exists
  ansible.builtin.file:
    path: "{{ install_path }}/masterserver/"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "755"

- name: Extract master server zip onto server if the path doesn't exist
  ansible.builtin.unarchive:
    creates: "{{ install_path }}/masterserver/System/"
    src: "{{ item }}"
    dest: "{{ install_path }}/masterserver/"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "744"
  with_fileglob:
    - "templates/masterserver/OldUnreal-UTPatch*"

- name: Copy files into the masterserver folder
  ansible.builtin.copy:
    src: "templates/masterserver/scripts/"
    dest: "{{ install_path }}/masterserver/System/"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "744"

- name: Create service files for the master server
  ansible.builtin.template:
    src: templates/masterserver/services/mobileforces-masterserver.j2
    dest: /etc/systemd/system/mobileforces-masterserver.service
    mode: "644"
  notify:
    - Reload systemctl
