---
- name: Extract master server zip onto server if the path doesn't exist
  ansible.builtin.unarchive:
    creates: "{{ game_path }}-masterserver/System64/"
    src: "{{ item }}"
    dest: "{{ game_path }}-masterserver/"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "774"
  with_fileglob:
    - "templates/masterserver/OldUnreal-UTPatch*-Linux-amd64.tar.bz2"

- name: Copy files into the masterserver folder
  ansible.builtin.copy:
    src: "templates/masterserver/scripts/{{ item }}"
    dest: "{{ game_path }}-masterserver/System64/{{ item }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "774"
  loop:
    - "MasterServer.ini"
    - "RunMasterServer.sh"

- name: Create service files for the master server
  ansible.builtin.template:
    src: templates/masterserver/services/mobileforces-masterserver.j2
    dest: /etc/systemd/system/mobileforces-masterserver.service
    mode: "644"
  notify:
    - Reload systemctl
