---
- name: Install qt5
  ansible.builtin.package:
    name: qtbase5-dev
    state: latest

- name: Ensure masterserver directories exist
  ansible.builtin.file:
    path: "{{ masterserver_path }}/{{ item }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "744"
  loop:
    - bin
    - data
    - WebInterface-Perl-MS-Qt5
    - WebInterface-Perl-MS-Qt5/s
    - WebInterface-Perl-MS-Qt5/s/style
    - WebInterface-Perl-MS-Qt5/s/style/{{ ServerName }}

- name: Clone master server web repository
  ansible.builtin.git:
    repo: https://github.com/333networks/WebInterface-Perl-MS-Qt5.git
    dest: "{{ masterserver_path }}/WebInterface-Perl-MS-Qt5"
    depth: 1
    force: true
  become: true
  become_user: "{{ server_user }}"

- name: Copy masterserver files
  ansible.builtin.copy:
    src: "templates/masterserver/{{ item[0] }}"
    dest: "{{ masterserver_path }}/{{ item[1] }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "744"
  loop:
    - [files/MasterServer-Qt5, bin/MasterServer-Qt5]
    - [files/body.gif, "WebInterface-Perl-MS-Qt5/s/style/{{ ServerName }}/body.gif"]
    - [files/MFLogo.png, "WebInterface-Perl-MS-Qt5/s/style/{{ ServerName }}/MFLogo.png"]
    - [scripts/SupportedGames.json, /data/SupportedGames.json]

- name: Copy masterserver configs
  ansible.builtin.template:
    src: "templates/masterserver/scripts/{{ item[0] }}"
    dest: "{{ masterserver_path }}/{{ item[1] }}"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: "744"
  loop:
    - [MasterServer-Settings.j2, data/MasterServer-Settings.ini]
    - [settings.j2, WebInterface-Perl-MS-Qt5/data/settings.pl]
    - [conf.j2, "WebInterface-Perl-MS-Qt5/s/style/{{ ServerName }}/conf"]

- name: Create masterserver style
  ansible.builtin.shell:
    cmd: perl "{{ masterserver_path }}/WebInterface-Perl-MS-Qt5/util/skingen.pl" "{{ ServerName }}"
    creates: "{{ masterserver_path }}/WebInterface-Perl-MS-Qt5/s/style/{{ ServerName }}/style.css"
  become: true
  become_user: "{{ server_user }}"

- name: Create service file for the master server
  ansible.builtin.template:
    src: templates/masterserver/services/mobileforces-masterserver.j2
    dest: /etc/systemd/system/mobileforces-masterserver.service
    mode: "644"
  register: service_file

- name: Create service file for the master server list country script
  ansible.builtin.template:
    src: templates/masterserver/services/mobileforces-masterserver-listcountry.j2
    dest: /etc/systemd/system/mobileforces-masterserver-listcountry.service
    mode: "644"
  register: service_file

- name: Reload systemctl
  ansible.builtin.command: systemctl daemon-reload
  when: service_file.changed
