name: CD

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: "Run Ansible in dry-run mode"
        required: false
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible-core

      - name: Configure SSH
        env:
          ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
        run: |
          # Save the private SSH key
          mkdir -p ~/.ssh
          echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the remote server's host key to known_hosts to avoid verification errors
          ssh-keyscan -H ${{ vars.SERVER_NAME }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy with Ansible
        env:
          SERVER_ADMIN: ${{ secrets.SERVER_ADMIN }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          KOFI_TOKEN: ${{ secrets.KOFI_TOKEN }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_SECRET_KEY: ${{ secrets.PAYPAL_SECRET_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          # Construct ansible-playbook command
          command="ansible-playbook playbook.yml -u root -i ${{ vars.SERVER_NAME }}, \
            -e \"MasterName=${{ vars.MASTER_NAME }} ServerName=${{ vars.SERVER_NAME }} \
              ServerAdmin=$SERVER_ADMIN AdminName=${{ vars.ADMIN_NAME }} AdminPassword=$ADMIN_PASSWORD \
              kofi_token=$KOFI_TOKEN paypal_clientid=$PAYPAL_CLIENT_ID \
              paypal_secretkey=$PAYPAL_SECRET_KEY app_secret=$APP_SECRET\""

          # Add dry-run option if specified
          if $DRY_RUN; then
            command="$command --check"
          fi

          # Run the Ansible playbook
          eval $command
